//#include <sstream>
#pragma once
// Definición del mapa de DLMS_CONFORMANCE
std::unordered_map<std::string, DLMS_CONFORMANCE> dlmsConformanceMap = {
    {"DLMS_CONFORMANCE_GENERAL_PROTECTION", DLMS_CONFORMANCE_GENERAL_PROTECTION},
    {"DLMS_CONFORMANCE_GENERAL_BLOCK_TRANSFER", DLMS_CONFORMANCE_GENERAL_BLOCK_TRANSFER},
    {"DLMS_CONFORMANCE_ATTRIBUTE_0_SUPPORTED_WITH_SET", DLMS_CONFORMANCE_ATTRIBUTE_0_SUPPORTED_WITH_SET},
    {"DLMS_CONFORMANCE_PRIORITY_MGMT_SUPPORTED", DLMS_CONFORMANCE_PRIORITY_MGMT_SUPPORTED},
    {"DLMS_CONFORMANCE_ATTRIBUTE_0_SUPPORTED_WITH_GET", DLMS_CONFORMANCE_ATTRIBUTE_0_SUPPORTED_WITH_GET},
    {"DLMS_CONFORMANCE_BLOCK_TRANSFER_WITH_GET_OR_READ", DLMS_CONFORMANCE_BLOCK_TRANSFER_WITH_GET_OR_READ},
    {"DLMS_CONFORMANCE_BLOCK_TRANSFER_WITH_SET_OR_WRITE", DLMS_CONFORMANCE_BLOCK_TRANSFER_WITH_SET_OR_WRITE},
    {"DLMS_CONFORMANCE_BLOCK_TRANSFER_WITH_ACTION", DLMS_CONFORMANCE_BLOCK_TRANSFER_WITH_ACTION},
    {"DLMS_CONFORMANCE_MULTIPLE_REFERENCES", DLMS_CONFORMANCE_MULTIPLE_REFERENCES},
    {"DLMS_CONFORMANCE_DATA_NOTIFICATION", DLMS_CONFORMANCE_DATA_NOTIFICATION},
    {"DLMS_CONFORMANCE_ACCESS", DLMS_CONFORMANCE_ACCESS},
    {"DLMS_CONFORMANCE_GET", DLMS_CONFORMANCE_GET},
    {"DLMS_CONFORMANCE_SET", DLMS_CONFORMANCE_SET},
    {"DLMS_CONFORMANCE_SELECTIVE_ACCESS", DLMS_CONFORMANCE_SELECTIVE_ACCESS},
    {"DLMS_CONFORMANCE_EVENT_NOTIFICATION", DLMS_CONFORMANCE_EVENT_NOTIFICATION},
    {"DLMS_CONFORMANCE_ACTION", DLMS_CONFORMANCE_ACTION},
    {"DLMS_CONFORMANCE_NONE",DLMS_CONFORMANCE_NONE},
    {"DLMS_CONFORMANCE_RESERVED_ZERO",DLMS_CONFORMANCE_RESERVED_ZERO},
    {"DLMS_CONFORMANCE_READ",DLMS_CONFORMANCE_READ},
    {"DLMS_CONFORMANCE_WRITE",DLMS_CONFORMANCE_WRITE},
    {"DLMS_CONFORMANCE_UN_CONFIRMED_WRITE",DLMS_CONFORMANCE_UN_CONFIRMED_WRITE},
    {"DLMS_CONFORMANCE_DELTA_VALUE_ENCODING",DLMS_CONFORMANCE_DELTA_VALUE_ENCODING},
    {"DLMS_CONFORMANCE_RESERVED_SEVEN",DLMS_CONFORMANCE_RESERVED_SEVEN},
    {"DLMS_CONFORMANCE_INFORMATION_REPORT",DLMS_CONFORMANCE_INFORMATION_REPORT},
    {"DLMS_CONFORMANCE_PARAMETERIZED_ACCESS",DLMS_CONFORMANCE_PARAMETERIZED_ACCESS}
    
};

std::unordered_map<std::string, DLMS_SERVICE_CLASS> dlmsserviceclassmap = {
    {"DLMS_SERVICE_CLASS_CONFIRMED",DLMS_SERVICE_CLASS_CONFIRMED},
    {"DLMS_SERVICE_CLASS_UN_CONFIRMED",DLMS_SERVICE_CLASS_UN_CONFIRMED}
};

std::unordered_map<std::string, DATETIME_SKIPS> dlmsdatetimeskipsmap = {
    {"DATETIME_SKIPS_NONE", DATETIME_SKIPS_NONE},
    {"DATETIME_SKIPS_YEAR", DATETIME_SKIPS_YEAR},
    {"DATETIME_SKIPS_MONTH", DATETIME_SKIPS_MONTH},
    {"DATETIME_SKIPS_DAY", DATETIME_SKIPS_DAY},
    {"DATETIME_SKIPS_DAYOFWEEK", DATETIME_SKIPS_DAYOFWEEK},
    {"DATETIME_SKIPS_HOUR", DATETIME_SKIPS_HOUR},
    {"DATETIME_SKIPS_MINUTE", DATETIME_SKIPS_MINUTE},
    {"DATETIME_SKIPS_SECOND", DATETIME_SKIPS_SECOND},
    {"DATETIME_SKIPS_MS", DATETIME_SKIPS_MS},
    {"DATETIME_SKIPS_DEVITATION", DATETIME_SKIPS_DEVITATION},
    {"DATETIME_SKIPS_STATUS", DATETIME_SKIPS_STATUS}
};

std::unordered_map<std::string, DLMS_SECURITY> dlmssecuritymap = {
    {"DLMS_SERVICE_CLASS_CONFIRMED",DLMS_SECURITY_NONE},
    {"DLMS_SERVICE_CLASS_UN_CONFIRMED",DLMS_SECURITY_AUTHENTICATION},
    {"DLMS_SECURITY_ENCRYPTION",DLMS_SECURITY_ENCRYPTION},
    {"DLMS_SECURITY_AUTHENTICATION_ENCRYPTION",DLMS_SECURITY_AUTHENTICATION_ENCRYPTION}
};
